# Clean the data set for modeling

## Add WH, WHsin, and dummy variables

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df_main = pd.read_csv('/home/colili/Documents/PhD/project_john/DataFrame_produced_clean/df_slope_point.csv', index_col=0)
df_main.drop(columns=['index'], inplace=True)

/home/colili/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (23,24) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
df_main['WHsin'] = df_main['thickness']*df_main['width_centerline']*np.sin(df_main['Bed_slope'])

In [4]:
df_main['WH']=df_main['thickness']/df_main['width_centerline']

In [5]:
df_main['dummy']=np.random.rand(df_main.shape[0])

In [6]:
df_main.columns

Index(['rgiid', 'x', 'y', 'Surge', 'BgnDate', 'EndDate', 'CenLon', 'CenLat',
       'Area', 'Zmin', 'Zmax', 'Zmed', 'Slope', 'Aspect', 'Lmax', 'Status',
       'Connect', 'Form', 'TermType', 'Linkages', 'Name', 'check_geom',
       'geometry', 'bed', 'thickness', 'surface_elevation', 'width_centerline',
       'Runoff', 'ELA', 'beta', 'cmb', 'Bed_slope', 'Surface_slope', 'WHsin',
       'WH', 'dummy'],
      dtype='object')

## Recalculate SMB with beta, H and ELA

In [7]:
df_main['SMB_calc'] = df_main['beta']*(df_main['surface_elevation']-df_main['ELA'])

## Drop glaciers shorter than km

In [8]:
df_main = df_main[df_main.Lmax > 1000].copy()

## Drop glaciers that already melt away (A<km2)

In [9]:
df_main = df_main[df_main.Area > 1].copy()

## Drop surge index=9 (not present in Svalbard)

In [10]:
df_main.drop(df_main[df_main['Surge']==9].index, inplace=True)

## Convert surge index

In [11]:
df_main['Surge'] = df_main['Surge'].replace({3: 1, 2:1})

In [12]:
df_main.head()

,rgiid,x,y,Surge,BgnDate,EndDate,CenLon,CenLat,Area,Zmin,...,Runoff,ELA,beta,cmb,Bed_slope,Surface_slope,WHsin,WH,dummy,SMB_calc
204,RGI60-07.00004,524634.335707,8.539882e+06,0,20080901,-9999999,15.9932,76.9423,1.044,665,...,1.110227,431.471268,0.005068,1.388794,NaN,NaN,NaN,NaN,0.606833,NaN
205,RGI60-07.00004,524633.930457,8.539906e+06,0,20080901,-9999999,15.9932,76.9423,1.044,665,...,1.105706,431.784498,0.005069,1.394411,NaN,NaN,NaN,NaN,0.853305,NaN
206,RGI60-07.00004,524657.521964,8.539931e+06,0,20080901,-9999999,15.9932,76.9423,1.044,665,...,1.100061,432.103017,0.005069,1.392706,NaN,NaN,NaN,0.090480,0.591868,2.447634
207,RGI60-07.00004,524681.113471,8.539955e+06,0,20080901,-9999999,15.9932,76.9423,1.044,665,...,1.094416,432.421537,0.005068,1.391001,12.654898,3.372262,809.523242,0.104519,0.745581,2.435692
208,RGI60-07.00004,524704.704977,8.539980e+06,0,20080901,-9999999,15.9932,76.9423,1.044,665,...,1.088771,432.740057,0.005068,1.389296,12.654898,3.372262,904.899185,0.093502,0.484789,2.433887

In [13]:
df_main.columns

Index(['rgiid', 'x', 'y', 'Surge', 'BgnDate', 'EndDate', 'CenLon', 'CenLat',
       'Area', 'Zmin', 'Zmax', 'Zmed', 'Slope', 'Aspect', 'Lmax', 'Status',
       'Connect', 'Form', 'TermType', 'Linkages', 'Name', 'check_geom',
       'geometry', 'bed', 'thickness', 'surface_elevation', 'width_centerline',
       'Runoff', 'ELA', 'beta', 'cmb', 'Bed_slope', 'Surface_slope', 'WHsin',
       'WH', 'dummy', 'SMB_calc'],
      dtype='object')

In [14]:
df_main.set_index(['rgiid','x', 'y'], inplace=True)

In [15]:
df_main.head()

                                           Surge   BgnDate  EndDate   CenLon  \
rgiid          x             y
RGI60-07.00004 524634.335707 8.539882e+06      0  20080901 -9999999  15.9932
               524633.930457 8.539906e+06      0  20080901 -9999999  15.9932
               524657.521964 8.539931e+06      0  20080901 -9999999  15.9932
               524681.113471 8.539955e+06      0  20080901 -9999999  15.9932
               524704.704977 8.539980e+06      0  20080901 -9999999  15.9932

                                            CenLat   Area  Zmin  Zmax  Zmed  \
rgiid          x             y
RGI60-07.00004 524634.335707 8.539882e+06  76.9423  1.044   665   933   799
               524633.930457 8.539906e+06  76.9423  1.044   665   933   799
               524657.521964 8.539931e+06  76.9423  1.044   665   933   799
               524681.113471 8.539955e+06  76.9423  1.044   665   933   799
               524704.704977 8.539980e+06  76.9423  1.044   665   933   799

                                           Slope  ...    Runoff         ELA  \
rgiid          x             y                    ...
RGI60-07.00004 524634.335707 8.539882e+06   13.8  ...  1.110227  431.471268
               524633.930457 8.539906e+06   13.8  ...  1.105706  431.784498
               524657.521964 8.539931e+06   13.8  ...  1.100061  432.103017
               524681.113471 8.539955e+06   13.8  ...  1.094416  432.421537
               524704.704977 8.539980e+06   13.8  ...  1.088771  432.740057

                                               beta       cmb  Bed_slope  \
rgiid          x             y
RGI60-07.00004 524634.335707 8.539882e+06  0.005068  1.388794        NaN
               524633.930457 8.539906e+06  0.005069  1.394411        NaN
               524657.521964 8.539931e+06  0.005069  1.392706        NaN
               524681.113471 8.539955e+06  0.005068  1.391001  12.654898
               524704.704977 8.539980e+06  0.005068  1.389296  12.654898

                                           Surface_slope       WHsin  \
rgiid          x             y
RGI60-07.00004 524634.335707 8.539882e+06            NaN         NaN
               524633.930457 8.539906e+06            NaN         NaN
               524657.521964 8.539931e+06            NaN         NaN
               524681.113471 8.539955e+06       3.372262  809.523242
               524704.704977 8.539980e+06       3.372262  904.899185

                                                 WH     dummy  SMB_calc
rgiid          x             y
RGI60-07.00004 524634.335707 8.539882e+06       NaN  0.606833       NaN
               524633.930457 8.539906e+06       NaN  0.853305       NaN
               524657.521964 8.539931e+06  0.090480  0.591868  2.447634
               524681.113471 8.539955e+06  0.104519  0.745581  2.435692
               524704.704977 8.539980e+06  0.093502  0.484789  2.433887

[5 rows x 34 columns]

In [16]:
df_main.to_csv('/home/colili/Documents/PhD/project_john/DataFrame_produced_clean/df_modelling.csv')